'use strict';function v(e,a,b,c){e.A.ec(e.Ta,a,b,c,void 0)}function z(e,a,b,c){e.A.Ma?v(e,a,b,c):e.A.df()._OnMessageFromDOM({type:"event",component:e.Ta,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function A(e,a,b){e.A.B(e.Ta,a,b)}function B(e,a){for(const [b,c]of a)A(e,b,c)}function C(e){e.Kb||(e.A.Pe(e.Vd),e.Kb=!0)}window.xa=class{constructor(e,a){this.A=e;this.Ta=a;this.Kb=!1;this.Vd=()=>this.Aa()}Zc(){}Aa(){}};function D(e){-1!==e.La&&(self.clearTimeout(e.La),e.La=-1)}
window.Ge=class{constructor(e,a){this.Ec=e;this.qg=a;this.La=-1;this.Lb=-Infinity;this.Wd=()=>{this.La=-1;this.Lb=Date.now();this.Ya=!0;this.Ec();this.Ya=!1};this.Fd=this.Ya=!1}c(){D(this);this.Wd=this.Ec=null}};"use strict";function E(e,a){const b=a.elementId,c=e.cd(b,a);e.Y.set(b,c);a.isVisible||(c.style.display="none");c.addEventListener("focus",()=>{F(e,"elem-focused",b)});c.addEventListener("blur",()=>{F(e,"elem-blurred",b)});e.Fb&&document.body.appendChild(c)}
function G(e,a,b){A(e,a,c=>{const g=e.Y.get(c.elementId);return b(g,c)})}function F(e,a,b,c){c||(c={});c.elementId=b;v(e,a,c)}function H(e,a,b){var c;c||(c={});c.elementId=b;z(e,a,c)}
window.pe=class extends self.xa{constructor(e,a){super(e,a);this.Y=new Map;this.Fb=!0;B(this,[["create",b=>E(this,b)],["destroy",b=>{{b=b.elementId;const c=this.Y.get(b);this.Fb&&c.parentElement.removeChild(c);this.Y.delete(b)}}],["set-visible",b=>{this.Fb&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Fb){var c=this.Y.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";b=b.fontSize;
null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{{const c=this.Y.get(b.elementId);this.lc(c,b)}}],["focus",b=>this.zc(b)],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);G(this,"get-element",b=>b)}cd(){throw Error("required override");}lc(){throw Error("required override");}zc(e){const a=this.Y.get(e.elementId);e.focus?a.focus():
a.blur()}};"use strict";
{var I=function(q){return l.has(q)},J=function(q){return new Promise((f,k)=>{const m=new FileReader;m.onload=r=>f(r.target.result);m.onerror=r=>k(r);m.readAsArrayBuffer(q)})},K=async function(q){q=await J(q);return(new TextDecoder("utf-8")).decode(q)},L=function(q){if(q.Ag){const f=document.createElement("script");f.async=!1;f.textContent=q.Dg;document.head.appendChild(f)}else return new Promise((f,k)=>{const m=document.createElement("script");m.onload=f;m.onerror=k;m.async=!1;m.src=q;document.head.appendChild(m)})};
const e=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=new Audio;const b={"audio/webm; codecs=opus":!!a.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!a.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!a.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!a.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!a.canPlayType("audio/mp4"),"audio/mpeg":!!a.canPlayType("audio/mpeg")};a=null;const c=[];let g=0;window.RealFile=
window.File;const p=[],t=new Map,d=new Map;let h=0;const n=[];self.Og=function(q){if("function"!==typeof q)throw Error("runOnStartup called without a function");n.push(q)};const l=new Set(["cordova","playable-ad","instant-games"]);window.qa=class q{constructor(f){this.Ma=f.Fg;this.ma=null;this.W="";this.Tc=f.Cg;this.mb={};this.Ea=this.lb=null;this.Ib=[];this.$a=this.I=this.Ja=null;this.Ia=-1;this.vg=()=>this.Bf();this.Ha=[];this.J=f.Xd;I(this.J)&&this.Ma&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this.Ma=!1);this.Wc=!1;this.Nb=this.ha=null;"html5"!==this.J&&"playable-ad"!==this.J||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.B("runtime","cordova-fetch-local-file",k=>this.lf(k));this.B("runtime","create-job-worker",()=>this.mf());"cordova"===this.J?document.addEventListener("deviceready",()=>this.td(f)):this.td(f)}c(){this.mc();this.ma&&
(this.ma=this.ma.onmessage=null);this.lb&&(this.lb.terminate(),this.lb=null);this.Ea&&(this.Ea.c(),this.Ea=null);this.I&&(this.I.parentElement.removeChild(this.I),this.I=null)}gd(){return e&&"cordova"===this.J}qb(){return e&&I(this.J)||navigator.standalone}async td(f){if("playable-ad"===this.J){this.ha=self.c3_base64files;this.Nb={};await this.Ue();for(let m=0,r=f.Na.length;m<r;++m){var k=f.Na[m].toLowerCase();this.Nb.hasOwnProperty(k)?f.Na[m]={Ag:!0,Dg:this.Nb[k]}:this.ha.hasOwnProperty(k)&&(f.Na[m]=
URL.createObjectURL(this.ha[k]))}}f.xg?this.W=f.xg:(k=location.origin,this.W=("null"===k?"file:///":k)+location.pathname,k=this.W.lastIndexOf("/"),-1!==k&&(this.W=this.W.substr(0,k+1)));if(f.Hg)for(const [m,r]of Object.entries(f.Hg))this.mb[m]=URL.createObjectURL(r);k=new MessageChannel;this.ma=k.port1;this.ma.onmessage=m=>this._OnMessageFromRuntime(m.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(m=>this.xf(m));this.$a=new self.Ce(this);await this.$a.ye();this.hd();"object"===
typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();await this.jg();this.Ma?await this.ff(f,k.port2):await this.ef(f,k.port2)}pc(f){return this.mb.hasOwnProperty(f)?this.mb[f]:f.endsWith("/workermain.js")&&this.mb.hasOwnProperty("workermain.js")?this.mb["workermain.js"]:"playable-ad"===this.J&&this.ha.hasOwnProperty(f.toLowerCase())?URL.createObjectURL(this.ha[f.toLowerCase()]):f}async Yb(f,k,m){if(f.startsWith("blob:"))return new Worker(f,
m);if(this.gd()&&"file:"===location.protocol)return f=await this.Xb(this.Tc+f),new Worker(URL.createObjectURL(new Blob([f],{type:"application/javascript"})),m);f=new URL(f,k);if(location.origin!==f.origin){f=await fetch(f);if(!f.ok)throw Error("failed to fetch worker script");f=await f.blob();return new Worker(URL.createObjectURL(f),m)}return new Worker(f,m)}hd(){if(this.qb()){const f=document.documentElement.style,k=document.body.style,m=window.innerWidth<window.innerHeight,r=m?window.screen.width:
window.screen.height;k.height=f.height=(m?window.screen.height:window.screen.width)+"px";k.width=f.width=r+"px"}}sd(f){return{baseUrl:this.W,windowInnerWidth:window.innerWidth,windowInnerHeight:window.innerHeight,devicePixelRatio:window.devicePixelRatio,isFullscreen:q.dc(),projectData:f.Ng,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:f.Xd,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Mg,jobScheduler:this.$a.we(),
supportedAudioFormats:b,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Tc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Tc+"opus.wasm.wasm",isiOSCordova:this.gd(),isiOSWebView:this.qb(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async ff(f,k){var m=this.pc(f.Gg);this.lb=await this.Yb(m,this.W,{name:"Runtime"});this.I=document.createElement("canvas");this.I.style.display="none";m=this.I.transferControlToOffscreen();document.body.appendChild(this.I);window.c3canvas=
this.I;this.lb.postMessage(Object.assign(this.sd(f),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:m,workerDependencyScripts:f.Yc||[],engineScripts:f.Na,projectScripts:window.Lg,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,m,...this.$a.xe()]);this.Ib=p.map(r=>new r(this));this.rd();self.c3_callFunction=(r,u)=>this.Ja.gf(r,u);"preview"===this.J&&(self.goToLastErrorScript=()=>this.ec("runtime","go-to-last-error-script"))}async ef(f,k){this.I=document.createElement("canvas");this.I.style.display=
"none";document.body.appendChild(this.I);window.c3canvas=this.I;this.Ib=p.map(r=>new r(this));this.rd();const m=f.Na.map(r=>"string"===typeof r?(new URL(r,this.W)).toString():r);Array.isArray(f.Yc)&&m.unshift(...f.Yc);await Promise.all(m.map(r=>L(r)));if(f.Yd&&0<f.Yd.length){const r=self.C3_ProjectScriptsStatus;try{if(await Promise.all(f.Yd.map(u=>L(u[1]))),Object.values(r).some(u=>!u)){self.setTimeout(()=>this.Ad(r),100);return}}catch(u){console.error("[Preview] Error loading project scripts: ",
u);self.setTimeout(()=>this.Ad(r),100);return}}"preview"===this.J&&"object"!==typeof self.Ig.Jg?(console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(f=Object.assign(this.sd(f),{isInWorker:!1,messagePort:k,canvas:this.I,runOnStartupFunctions:n}),this.Ea=self.C3_CreateRuntime(f),await self.C3_InitRuntime(this.Ea,f))}Ad(f){f=
`Failed to load project script '${Object.entries(f).filter(k=>!k[1]).map(k=>k[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+f);alert(f)}async mf(){const f=await this.$a.qd();return{outputPort:f,transferables:[f]}}df(){if(this.Ma)throw Error("not available in worker mode");return this.Ea}ec(f,k,m,r,u){this.ma.postMessage({type:"event",component:f,handler:k,dispatchOpts:r||null,data:m,responseId:null},this.Wc?void 0:u)}jd(f,k,m,r,u){const x=h++,w=new Promise((y,
V)=>{d.set(x,{resolve:y,reject:V})});this.ma.postMessage({type:"event",component:f,handler:k,dispatchOpts:r||null,data:m,responseId:x},this.Wc?void 0:u);return w}["_OnMessageFromRuntime"](f){const k=f.type;if("event"===k)return this.sf(f);if("result"===k)this.Ef(f);else if("runtime-ready"===k)this.Ff();else if("alert"===k)alert(f.message);else throw Error(`unknown message '${k}'`);}sf(f){const k=f.component,m=f.handler,r=f.data,u=f.responseId;if(f=t.get(k))if(f=f.get(m)){var x=null;try{x=f(r)}catch(w){console.error(`Exception in '${k}' handler '${m}':`,
w);null!==u&&this.Ab(u,!1,""+w);return}if(null===u)return x;x&&x.then?x.then(w=>this.Ab(u,!0,w)).catch(w=>{console.error(`Rejection from '${k}' handler '${m}':`,w);this.Ab(u,!1,""+w)}):this.Ab(u,!0,x)}else console.warn(`[DOM] No handler '${m}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Ab(f,k,m){let r;m&&m.transferables&&(r=m.transferables);this.ma.postMessage({type:"result",responseId:f,isOk:k,result:m},r)}Ef(f){const k=f.responseId,m=f.isOk;f=f.result;
const r=d.get(k);m?r.resolve(f):r.reject(f);d.delete(k)}B(f,k,m){let r=t.get(f);r||(r=new Map,t.set(f,r));if(r.has(k))throw Error(`[DOM] Component '${f}' already has handler '${k}'`);r.set(k,m)}static wa(f){if(p.includes(f))throw Error("DOM handler already added");p.push(f)}rd(){for(const f of this.Ib)if("runtime"===f.Ta){this.Ja=f;return}throw Error("cannot find runtime DOM handler");}xf(f){this.ec("debugger","message",f)}Ff(){for(const f of this.Ib)f.Zc()}static dc(){return!!(document.fullscreenElement||
document.webkitFullscreenElement||document.mozFullScreenElement)}Pe(f){this.Ha.push(f);this.Cc()}Qf(f){f=this.Ha.indexOf(f);if(-1===f)throw Error("invalid callback");this.Ha.splice(f,1);this.Ha.length||this.mc()}Cc(){-1===this.Ia&&this.Ha.length&&(this.Ia=requestAnimationFrame(this.vg))}mc(){-1!==this.Ia&&(cancelAnimationFrame(this.Ia),this.Ia=-1)}Bf(){this.Ia=-1;for(const f of this.Ha)f();this.Cc()}ra(f){this.Ja.ra(f)}za(f){this.Ja.za(f)}Bc(){this.Ja.Bc()}tb(f){this.Ja.tb(f)}Ae(){return!!b["audio/webm; codecs=opus"]}async og(f){f=
await this.jd("runtime","opus-decode",{arrayBuffer:f},null,[f]);return new Float32Array(f)}ze(f){return/^(?:[a-z]+:)?\/\//.test(f)||"data:"===f.substr(0,5)||"blob:"===f.substr(0,5)}Be(f){return!this.ze(f)}async lf(f){const k=f.filename;switch(f.as){case "text":return await this.oe(k);case "buffer":return await this.Xb(k);default:throw Error("unsupported type");}}bd(f){const k=window.cordova.file.applicationDirectory+"www/"+f.toLowerCase();return new Promise((m,r)=>{window.resolveLocalFileSystemURL(k,
u=>{u.file(m,r)},r)})}async oe(f){f=await this.bd(f);return await K(f)}nc(){if(c.length&&!(8<=g)){g++;var f=c.shift();this.Ve(f.filename,f.Eg,f.zg)}}Xb(f){return new Promise((k,m)=>{c.push({filename:f,Eg:r=>{g--;this.nc();k(r)},zg:r=>{g--;this.nc();m(r)}});this.nc()})}async Ve(f,k,m){try{const r=await this.bd(f),u=await J(r);k(u)}catch(r){m(r)}}async Ue(){const f=[];for(const [k,m]of Object.entries(this.ha))f.push(this.Te(k,m));await Promise.all(f)}async Te(f,k){if("object"===typeof k)this.ha[f]=
new Blob([k.str],{type:k.type}),this.Nb[f]=k.str;else{let m=await this.bf(k);m||(m=this.Xe(k));this.ha[f]=m}}async bf(f){try{return await (await fetch(f)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}Xe(f){f=this.Kf(f);return this.Se(f.data,f.Bg)}Kf(f){var k=f.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");
var m=f.substring(k+1);k=f.substring(5,k).split(";");f=k[0]||"";const r=k[2];m="base64"===k[1]||"base64"===r?atob(m):decodeURIComponent(m);return{Bg:f,data:m}}Se(f,k){var m=f.length;let r=m>>2,u=new Uint8Array(m),x=new Uint32Array(u.buffer,0,r),w,y;for(y=w=0;w<r;++w)x[w]=f.charCodeAt(y++)|f.charCodeAt(y++)<<8|f.charCodeAt(y++)<<16|f.charCodeAt(y++)<<24;for(m&=3;m--;)u[y]=f.charCodeAt(y),++y;return new Blob([u],{type:k})}jg(){let f=null;const k=new Promise(u=>f=u),m=new ArrayBuffer(1),r=new MessageChannel;
r.port2.onmessage=u=>{u.data&&u.data.arrayBuffer||(this.Wc=!0,console.warn("MessageChannel transfers determined to be broken. Disabling transferables."));f()};r.port1.postMessage({arrayBuffer:m},[m]);return k}}}"use strict";
{var N=function(){const d=document.activeElement;if(!d)return!1;const h=d.tagName.toLowerCase(),n=new Set("email number password search tel text url".split(" "));return"textarea"===h?!0:"input"===h?n.has(d.type.toLowerCase()||"text"):M(d)},O=function(){try{return window.parent&&window.parent.document.hasFocus()}catch(d){return!1}},P=function(d){(d.metaKey||d.ctrlKey)&&d.preventDefault()},Q=function(d){p.has(d.target.tagName.toLowerCase())&&d.preventDefault()},M=function(d){do{if(d.parentNode&&d.hasAttribute("contenteditable"))return!0;
d=d.parentNode}while(d);return!1},T=async function(d,h,n){if(!/firefox/i.test(navigator.userAgent))return await R(d);var l=await S(d);l=(new DOMParser).parseFromString(l,"image/svg+xml");const q=l.documentElement;if(q.hasAttribute("width")&&q.hasAttribute("height")){const f=q.getAttribute("width"),k=q.getAttribute("height");if(!f.includes("%")&&!k.includes("%"))return await R(d)}q.setAttribute("width",h+"px");q.setAttribute("height",n+"px");l=(new XMLSerializer).serializeToString(l);d=new Blob([l],
{type:"image/svg+xml"});return await R(d)},S=function(d){return new Promise((h,n)=>{let l=new FileReader;l.onload=q=>h(q.target.result);l.onerror=q=>n(q);l.readAsText(d)})},R=async function(d){d=URL.createObjectURL(d);try{return await aa(d)}finally{URL.revokeObjectURL(d)}},aa=function(d){return new Promise((h,n)=>{const l=new Image;l.onload=()=>h(l);l.onerror=q=>n(q);l.src=d})},ba=function(d){return new Promise((h,n)=>{const l=document.createElement("link");l.onload=()=>h(l);l.onerror=q=>n(q);l.rel=
"stylesheet";l.href=d;document.head.appendChild(l)})},U=function(d){return d.sourceCapabilities&&d.sourceCapabilities.firesTouchEvents||d.originalEvent&&d.originalEvent.sourceCapabilities&&d.originalEvent.sourceCapabilities.firesTouchEvents};const e=self.qa,a=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),b={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},c={dispatchUserScriptEvent:!0},g={dispatchRuntimeEvent:!0},p=new Set(["canvas","body","html"]);self.C3_GetSvgImageSize=async function(d){d=
await R(d);if(0<d.width&&0<d.height)return[d.width,d.height];{d.style.position="absolute";d.style.left="0px";d.style.top="0px";d.style.visibility="hidden";document.body.appendChild(d);const h=d.getBoundingClientRect();document.body.removeChild(d);return[h.width,h.height]}};self.C3_RasterSvgImageBlob=async function(d,h,n,l,q){d=await T(d,h,n);const f=document.createElement("canvas");f.width=l;f.height=q;f.getContext("2d").drawImage(d,0,0,h,n);return f};let t=!1;document.addEventListener("pause",()=>
t=!0);document.addEventListener("resume",()=>t=!1);e.wa(class extends self.xa{constructor(d){super(d,"runtime");this.Kd=!0;this.Ka=-1;this.Uc="any";this.Bd=this.Cd=!1;this.Nc=this.ib=this.ta=null;d.B("canvas","update-size",l=>this.If(l));d.B("runtime","invoke-download",l=>this.vf(l));d.B("runtime","raster-svg-image",l=>this.Cf(l));d.B("runtime","get-svg-image-size",l=>this.uf(l));d.B("runtime","set-target-orientation",l=>this.Gf(l));d.B("runtime","register-sw",()=>this.Df());d.B("runtime","post-to-debugger",
l=>this.wd(l));d.B("runtime","go-to-script",l=>this.wd(l));d.B("runtime","before-start-ticking",()=>this.kf());d.B("runtime","debug-highlight",l=>this.nf(l));d.B("runtime","enable-device-orientation",()=>this.Re());d.B("runtime","enable-device-motion",()=>this.Qe());d.B("runtime","add-stylesheet",l=>this.jf(l));d.B("runtime","alert",l=>this.tc(l));const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",l=>{const q=l.target;h.has(q.tagName.toLowerCase())||M(q)||l.preventDefault()});
const n=d.I;window.addEventListener("selectstart",Q);window.addEventListener("gesturehold",Q);n.addEventListener("selectstart",Q);n.addEventListener("gesturehold",Q);window.addEventListener("touchstart",Q,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",Q,{passive:!1}),n.addEventListener("pointerdown",Q)):n.addEventListener("touchstart",Q);this.fb=0;window.addEventListener("mousedown",l=>{1===l.button&&l.preventDefault()});window.addEventListener("mousewheel",
P,{passive:!1});window.addEventListener("wheel",P,{passive:!1});window.addEventListener("resize",()=>this.Jf());d.qb()&&window.addEventListener("focusout",()=>{N()||(document.scrollingElement.scrollTop=0)});this.Fa=new Set;this.Ob=new WeakSet;this.la=!1}kf(){"cordova"===this.A.J?(document.addEventListener("pause",()=>this.Ac(!0)),document.addEventListener("resume",()=>this.Ac(!1))):document.addEventListener("visibilitychange",()=>this.Ac(document.hidden));return{isSuspended:!(!document.hidden&&!t)}}Zc(){window.addEventListener("focus",
()=>this.Bb("window-focus"));window.addEventListener("blur",()=>{this.Bb("window-blur",{parentHasFocus:O()});this.fb=0});window.addEventListener("fullscreenchange",()=>this.vc());window.addEventListener("webkitfullscreenchange",()=>this.vc());window.addEventListener("mozfullscreenchange",()=>this.vc());window.addEventListener("fullscreenerror",h=>this.wc(h));window.addEventListener("webkitfullscreenerror",h=>this.wc(h));window.addEventListener("mozfullscreenerror",h=>this.wc(h));window.addEventListener("keydown",
h=>this.vd("keydown",h));window.addEventListener("keyup",h=>this.vd("keyup",h));window.addEventListener("dblclick",h=>this.xc("dblclick",h,b));window.addEventListener("wheel",h=>this.zf(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",h=>{this.qc(h);this.Ra("pointerdown",h)}),this.A.Ma&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.ib=new self.Ge(()=>this.$e(),5),this.ib.Fd=!0,window.addEventListener("pointerrawupdate",h=>this.Af(h))):window.addEventListener("pointermove",
h=>this.Ra("pointermove",h)),window.addEventListener("pointerup",h=>this.Ra("pointerup",h)),window.addEventListener("pointercancel",h=>this.Ra("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.qc(h);this.yc("pointerdown",h)}),window.addEventListener("mousemove",h=>this.yc("pointermove",h)),window.addEventListener("mouseup",h=>this.yc("pointerup",h)),window.addEventListener("touchstart",h=>{this.qc(h);this.zb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.zb("pointermove",
h)),window.addEventListener("touchend",h=>this.zb("pointerup",h)),window.addEventListener("touchcancel",h=>this.zb("pointercancel",h)));const d=()=>this.Bc();window.addEventListener("pointerup",d,!0);window.addEventListener("touchend",d,!0);window.addEventListener("click",d,!0);window.addEventListener("keydown",d,!0);window.addEventListener("gamepadconnected",d,!0)}Bb(d,h){v(this,d,h||null,g)}xb(){return Math.max(window.innerWidth,1)}wb(){return Math.max(window.innerHeight,1)}Jf(){const d=this.xb(),
h=this.wb();this.Bb("window-resize",{innerWidth:d,innerHeight:h,devicePixelRatio:window.devicePixelRatio});this.A.qb()&&(-1!==this.Ka&&clearTimeout(this.Ka),this.xd(d,h,0))}Rf(d,h,n){-1!==this.Ka&&clearTimeout(this.Ka);this.Ka=setTimeout(()=>this.xd(d,h,n),48)}xd(d,h,n){const l=this.xb(),q=this.wb();this.Ka=-1;l!=d||q!=h?this.Bb("window-resize",{innerWidth:l,innerHeight:q,devicePixelRatio:window.devicePixelRatio}):10>n&&this.Rf(l,q,n+1)}Gf(d){this.Uc=d.targetOrientation}kg(){const d=this.Uc;if(screen.orientation&&
screen.orientation.lock)screen.orientation.lock(d).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(d):screen.webkitLockOrientation?h=screen.webkitLockOrientation(d):screen.mozLockOrientation?h=screen.mozLockOrientation(d):screen.msLockOrientation&&(h=screen.msLockOrientation(d));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}vc(){const d=
e.dc();d&&"any"!==this.Uc&&this.kg();v(this,"fullscreenchange",{isFullscreen:d,innerWidth:this.xb(),innerHeight:this.wb()})}wc(d){console.warn("[Construct 3] Fullscreen request failed: ",d);v(this,"fullscreenerror",{isFullscreen:e.dc(),innerWidth:this.xb(),innerHeight:this.wb()})}Ac(d){d?this.A.mc():this.A.Cc();v(this,"visibilitychange",{hidden:d})}vd(d,h){"Backspace"===h.key&&Q(h);const n=a.get(h.code)||h.code;z(this,d,{code:n,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,
metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},b)}zf(d){v(this,"wheel",{clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,deltaX:d.deltaX,deltaY:d.deltaY,deltaZ:d.deltaZ,deltaMode:d.deltaMode,timeStamp:d.timeStamp},b)}xc(d,h,n){U(h)||z(this,d,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},n)}yc(d,h){if(!U(h)){var n=this.fb;"pointerdown"===d&&0!==n?d="pointermove":"pointerup"===d&&0!==h.buttons&&
(d="pointermove");z(this,d,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:n,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},b);this.fb=h.buttons;this.xc(h.type,h,c)}}Ra(d,h){if(this.ib&&"pointermove"!==d){var n=this.ib;n.Ya||(D(n),n.Lb=Date.now())}n=0;"mouse"===h.pointerType&&(n=this.fb);z(this,d,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,
buttons:h.buttons,lastButtons:n,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},b);"mouse"===h.pointerType&&(n="mousemove","pointerdown"===d?n="mousedown":"pointerup"===d&&(n="pointerup"),this.xc(n,h,c),this.fb=h.buttons)}Af(d){this.Nc=d;d=this.ib;if(-1===d.La){var h=Date.now(),n=h-d.Lb,l=d.qg;n>=l&&d.Fd?(d.Lb=
h,d.Ya=!0,d.Ec(),d.Ya=!1):d.La=self.setTimeout(d.Wd,Math.max(l-n,4))}}$e(){this.Ra("pointermove",this.Nc);this.Nc=null}zb(d,h){for(let n=0,l=h.changedTouches.length;n<l;++n){const q=h.changedTouches[n];z(this,d,{pointerId:q.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:q.clientX,clientY:q.clientY,pageX:q.pageX,pageY:q.pageY,width:2*(q.radiusX||q.webkitRadiusX||0),height:2*(q.radiusY||q.webkitRadiusY||0),pressure:q.force||q.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,
twist:q.rotationAngle||0,timeStamp:h.timeStamp},b)}}qc(d){window!==window.top&&window.focus();this.ud(d.target)&&document.activeElement&&!this.ud(document.activeElement)&&document.activeElement.blur()}ud(d){return!d||d===document||d===window||d===document.body||"canvas"===d.tagName.toLowerCase()}Re(){this.Cd||(this.Cd=!0,window.addEventListener("deviceorientation",d=>this.qf(d)),window.addEventListener("deviceorientationabsolute",d=>this.rf(d)))}Qe(){this.Bd||(this.Bd=!0,window.addEventListener("devicemotion",
d=>this.pf(d)))}qf(d){v(this,"deviceorientation",{absolute:!!d.absolute,alpha:d.alpha||0,beta:d.beta||0,gamma:d.gamma||0,timeStamp:d.timeStamp,webkitCompassHeading:d.webkitCompassHeading,webkitCompassAccuracy:d.webkitCompassAccuracy},b)}rf(d){v(this,"deviceorientationabsolute",{absolute:!!d.absolute,alpha:d.alpha||0,beta:d.beta||0,gamma:d.gamma||0,timeStamp:d.timeStamp},b)}pf(d){let h=null;var n=d.acceleration;n&&(h={x:n.x||0,y:n.y||0,z:n.z||0});n=null;var l=d.accelerationIncludingGravity;l&&(n={x:l.x||
0,y:l.y||0,z:l.z||0});l=null;const q=d.rotationRate;q&&(l={alpha:q.alpha||0,beta:q.beta||0,gamma:q.gamma||0});v(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:n,rotationRate:l,interval:d.interval,timeStamp:d.timeStamp},b)}If(d){const h=this.A,n=h.I;n.style.width=d.styleWidth+"px";n.style.height=d.styleHeight+"px";n.style.marginLeft=d.marginLeft+"px";n.style.marginTop=d.marginTop+"px";h.hd();this.Kd&&(n.style.display="",this.Kd=!1)}vf(d){const h=d.url;d=d.filename;const n=document.createElement("a"),
l=document.body;n.textContent=d;n.href=h;n.download=d;l.appendChild(n);n.click();l.removeChild(n)}async Cf(d){var h=d.imageBitmapOpts;d=await self.C3_RasterSvgImageBlob(d.blob,d.imageWidth,d.imageHeight,d.surfaceWidth,d.surfaceHeight);h=h?await createImageBitmap(d,h):await createImageBitmap(d);return{imageBitmap:h,transferables:[h]}}async uf(d){return await self.C3_GetSvgImageSize(d.blob)}async jf(d){await ba(d.url)}Bc(){var d=[...this.Fa];this.Fa.clear();if(!this.la)for(const h of d)(d=h.play())&&
d.catch(()=>{this.Ob.has(h)||this.Fa.add(h)})}ra(d){if("function"!==typeof d.play)throw Error("missing play function");this.Ob.delete(d);let h;try{h=d.play()}catch(n){this.Fa.add(d);return}h&&h.catch(()=>{this.Ob.has(d)||this.Fa.add(d)})}za(d){this.Fa.delete(d);this.Ob.add(d)}tb(d){this.la=!!d}nf(d){if(d.show){this.ta||(this.ta=document.createElement("div"),this.ta.id="inspectOutline",document.body.appendChild(this.ta));var h=this.ta;h.style.display="";h.style.left=d.left-1+"px";h.style.top=d.top-
1+"px";h.style.width=d.width+2+"px";h.style.height=d.height+2+"px";h.textContent=d.name}else this.ta&&(this.ta.style.display="none")}Df(){window.C3_RegisterSW&&window.C3_RegisterSW()}wd(d){window.c3_postToMessagePort&&(d.from="runtime",window.c3_postToMessagePort(d))}gf(d,h){return this.A.jd(this.Ta,"js-invoke-function",{name:d,params:h},void 0,void 0)}tc(d){alert(d.message)}})}"use strict";
{const e=document.currentScript.src;self.Ce=class{constructor(a){this.Sb=a;this.W=e?e.substr(0,e.lastIndexOf("/")+1):a.W;this.sg=Math.min(navigator.hardwareConcurrency||2,16);this.Gc=null;this.Ld=[];this.Rc=this.Kc=null}async ye(){if(this.pg)throw Error("already initialised");this.pg=!0;var a=this.Sb.pc("dispatchworker.js");this.Gc=await this.Sb.Yb(a,this.W,{name:"DispatchWorker"});a=new MessageChannel;this.Kc=a.port1;this.Gc.postMessage({type:"_init","in-port":a.port2},[a.port2]);this.Rc=await this.qd()}async qd(){const a=
this.Ld.length;var b=this.Sb.pc("jobworker.js");b=await this.Sb.Yb(b,this.W,{name:"JobWorker"+a});const c=new MessageChannel,g=new MessageChannel;this.Gc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":g.port2},[c.port2,g.port2]);this.Ld.push(b);return g.port1}we(){return{inputPort:this.Kc,outputPort:this.Rc,maxNumWorkers:this.sg}}xe(){return[this.Kc,this.Rc]}}}"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.qa({Fg:!1,Gg:"workermain.js",Na:["scripts/c3runtime.js"],Cg:"scripts/",Yc:[],Xd:"html5"}));"use strict";
{const e=180/Math.PI;self.da=class extends self.xa{constructor(a){super(a,"audio");this.Hb=this.f=null;this.Jb=this.Jc=!1;this.na=()=>this.lg();this.ba=[];this.C=[];this.ga=null;this.Md="";this.Nd=-1;this.hb=new Map;this.Oc=1;this.la=!1;this.Vc=0;this.Ub=1;this.Hc=0;this.Pd="HRTF";this.Gd="inverse";this.Qd=600;this.Od=1E4;this.Sd=1;this.Id=this.Sc=!1;this.wg=this.A.Ae();this.ca=new Map;this.Ca=new Set;this.Lc=!1;this.Pc="";this.ua=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.yf(b,c);this.Gb=null;
self.C3Audio_GetOutputStream=()=>this.tf();self.C3Audio_DOMInterface=this;B(this,[["create-audio-context",b=>this.We(b)],["play",b=>this.Lf(b)],["stop",b=>this.hg(b)],["stop-all",()=>this.ig()],["set-paused",b=>this.ag(b)],["set-volume",b=>this.fg(b)],["fade-volume",b=>this.af(b)],["set-master-volume",b=>this.Zf(b)],["set-muted",b=>this.$f(b)],["set-silent",b=>this.cg(b)],["set-looping",b=>this.Yf(b)],["set-playback-rate",b=>this.bg(b)],["seek",b=>this.Sf(b)],["preload",b=>this.Mf(b)],["unload",b=>
this.mg(b)],["unload-all",()=>this.ng()],["set-suspended",b=>this.dg(b)],["add-effect",b=>this.od(b)],["set-effect-param",b=>this.Vf(b)],["remove-effects",b=>this.Of(b)],["tick",b=>this.Hf(b)],["load-state",b=>this.wf(b)]])}async We(a){a.isiOSCordova&&(this.Sc=!0);this.Vc=a.timeScaleMode;this.Pd=["equalpower","HRTF","soundfield"][a.panningModel];this.Gd=["linear","inverse","exponential"][a.distanceModel];this.Qd=a.refDistance;this.Od=a.maxDistance;this.Sd=a.rolloffFactor;var b={latencyHint:a.latencyHint};
if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.pd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.pd()};this.Hb=this.f.createGain();this.Hb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.Zb();try{await Promise.all(a.preloadList.map(c=>
this.vb(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}pd(){this.Jb||(this.Jc=!1,window.addEventListener("pointerup",this.na,!0),window.addEventListener("touchend",this.na,!0),window.addEventListener("click",this.na,!0),window.addEventListener("keydown",this.na,!0),this.Jb=!0)}Ye(){this.Jb&&(this.Jc=!0,window.removeEventListener("pointerup",this.na,!0),window.removeEventListener("touchend",this.na,!0),window.removeEventListener("click",
this.na,!0),window.removeEventListener("keydown",this.na,!0),this.Jb=!1)}lg(){if(!this.Jc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.Ye()}}V(){return this.f}Zb(){return this.f.currentTime}oa(){return this.Hb}ed(a){return(a=this.ca.get(a.toLowerCase()))?a[0].O():this.oa()}Zd(a,b){a=a.toLowerCase();let c=this.ca.get(a);c||(c=[],this.ca.set(a,c));b.Xf(c.length);
b.eg(a);c.push(b);this.zd(a)}zd(a){let b=this.oa();const c=this.ca.get(a);if(c&&c.length){b=c[0].O();for(let g=0,p=c.length;g<p;++g){const t=c[g];g+1===p?t.R(this.oa()):t.R(c[g+1].O())}}for(const g of this.ja(a))g.He(b);this.ua&&this.Pc===a&&(this.ua.disconnect(),this.ua.connect(b))}ob(){return this.Oc}pb(){return this.la}Wf(){this.Id=!0}re(a,b){return b?this.A.og(a).then(c=>{const g=this.f.createBuffer(1,c.length,48E3);g.getChannelData(0).set(c);return g}):new Promise((c,g)=>{this.f.decodeAudioData(a,
c,g)})}ra(a){this.A.ra(a)}za(a){this.A.za(a)}kd(a){let b=0;for(let c=0,g=this.C.length;c<g;++c){const p=this.C[c];this.C[b]=p;p.K===a?p.c():++b}this.C.length=b}Ie(){let a=0;for(let b=0,c=this.ba.length;b<c;++b){const g=this.ba[b];this.ba[a]=g;g.pa()?g.c():++a}this.ba.length=a}*ja(a){if(a)for(const b of this.C)self.da.se(b.$,a)&&(yield b);else this.ga&&!this.ga.S()&&(yield this.ga)}async vb(a,b,c,g,p){for(const t of this.ba)if(t.Pa()===b)return await W(t),t;if(p)return null;g&&(this.Sc||this.Id)&&
this.Ie();p="audio/webm; codecs=opus"===c&&!this.wg;g&&p&&this.Wf();a=!g||this.Sc||p?new self.me(this,a,b,c,g,p):new self.ke(this,a,b,c,g);this.ba.push(a);await W(a);return a}async oc(a,b,c,g,p){for(const t of this.C)if(t.Pa()===b&&(t.Wb()||p))return t.Ke(g),t;a=await this.vb(a,b,c,p);g="html5"===a.Dc?new self.le(a.i,a,g):new self.ne(a.i,a,g);this.C.push(g);return g}Oe(a){let b=this.hb.get(a);if(!b){let c=null;b={Xc:0,promise:new Promise(g=>c=g),resolve:c};this.hb.set(a,b)}b.Xc++}Pf(a){const b=this.hb.get(a);
if(!b)throw Error("expected pending tag");b.Xc--;0===b.Xc&&(b.resolve(),this.hb.delete(a))}kc(a){a||(a=this.Md);return(a=this.hb.get(a))?a.promise:Promise.resolve()}yb(){if(0<this.Ca.size)C(this);else for(const a of this.C)if(a.fd()){C(this);break}}Aa(){for(var a of this.Ca)a.Aa();a=this.Zb();for(var b of this.C)b.Aa(a);b=this.C.filter(c=>c.fd()).map(c=>c.Oa());v(this,"state",{tickCount:this.Nd,audioInstances:b,analysers:[...this.Ca].map(c=>c.ue())});0===b.length&&0===this.Ca.size&&this.Kb&&(this.A.Qf(this.Vd),
this.Kb=!1)}fc(a,b,c){v(this,"trigger",{type:a,tag:b,aiid:c})}async Lf(a){const b=a.originalUrl,c=a.url,g=a.type,p=a.isMusic,t=a.tag,d=a.isLooping,h=a.vol,n=a.pos,l=a.panning;let q=a.off;0<q&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),q=q-a.performanceTime/1E3+a.contextTime):q=q-performance.now()/1E3+this.f.currentTime);this.Md=t;this.Oe(t);try{this.ga=await this.oc(b,c,g,t,p),l?(this.ga.sb(!0),this.ga.Je(l.x,l.y,l.angle,l.innerAngle,l.outerAngle,l.outerGain),l.hasOwnProperty("uid")&&
this.ga.Le(l.uid)):this.ga.sb(!1),this.ga.Play(d,h,n,q)}catch(f){console.error("[Construct 3] Audio: error starting playback: ",f);return}finally{this.Pf(t)}C(this)}hg(a){a=a.tag;for(const b of this.ja(a))b.ka()}ig(){for(const a of this.C)a.ka()}ag(a){const b=a.tag;a=a.paused;for(const c of this.ja(b))a?c.Qa():c.rb();this.yb()}fg(a){const b=a.tag;a=a.vol;for(const c of this.ja(b))c.ub(a)}async af(a){const b=a.tag,c=a.vol,g=a.duration;a=a.stopOnEnd;await this.kc(b);for(const p of this.ja(b))p.te(c,
g,a);this.yb()}Zf(a){this.Oc=a.vol;for(const b of this.C)b.Db()}$f(a){const b=a.tag;a=a.isMuted;for(const c of this.ja(b))c.ld(a)}cg(a){this.la=a.isSilent;this.A.tb(this.la);for(const b of this.C)b.Cb()}Yf(a){const b=a.tag;a=a.isLooping;for(const c of this.ja(b))c.ic(a)}async bg(a){const b=a.tag;a=a.rate;await this.kc(b);for(const c of this.ja(b))c.nd(a)}async Sf(a){const b=a.tag;a=a.pos;await this.kc(b);for(const c of this.ja(b))c.hc(a)}async Mf(a){const b=a.originalUrl,c=a.url,g=a.type;a=a.isMusic;
try{await this.oc(b,c,g,"",a)}catch(p){console.error("[Construct 3] Audio: error preloading: ",p)}}async mg(a){if(a=await this.vb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ba.indexOf(a),-1!==a&&this.ba.splice(a,1)}ng(){for(const a of this.ba)a.c();this.ba.length=0}dg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.C)b.jc(a);a&&this.f.suspend&&this.f.suspend()}Hf(a){this.Ub=a.timeScale;this.Hc=a.gameTime;this.Nd=a.tickCount;if(0!==this.Vc)for(var b of this.C)b.Ba();(b=a.listenerPos)&&
this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const g of this.C)g.fa===a&&g.md(c.x,c.y,c.angle)}}async od(a){var b=a.type;const c=a.tag;var g=a.params;if("filter"===b)g=new self.ee(this,...g);else if("delay"===b)g=new self.ce(this,...g);else if("convolution"===b){b=null;try{b=await this.vb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(p){console.log("[Construct 3] Audio: error loading convolution: ",p);return}g=new self.be(this,b.aa,...g);g.Tf(a.bufferOriginalUrl,
a.bufferType)}else if("flanger"===b)g=new self.fe(this,...g);else if("phaser"===b)g=new self.he(this,...g);else if("gain"===b)g=new self.ge(this,...g);else if("tremolo"===b)g=new self.je(this,...g);else if("ringmod"===b)g=new self.ie(this,...g);else if("distortion"===b)g=new self.de(this,...g);else if("compressor"===b)g=new self.ae(this,...g);else if("analyser"===b)g=new self.$d(this,...g);else throw Error("invalid effect type");this.Zd(c,g);this.yd()}Vf(a){const b=a.index,c=a.param,g=a.value,p=a.ramp,
t=a.time;a=this.ca.get(a.tag);!a||0>b||b>=a.length||(a[b].X(c,g,p,t),this.yd())}Of(a){a=a.tag.toLowerCase();const b=this.ca.get(a);if(b&&b.length){for(const c of b)c.c();this.ca.delete(a);this.zd(a)}}Ne(a){this.Ca.add(a);this.yb()}Nf(a){this.Ca.delete(a)}yd(){this.Lc||(this.Lc=!0,Promise.resolve().then(()=>this.Ze()))}Ze(){const a={};for(const [b,c]of this.ca)a[b]=c.map(g=>g.Oa());v(this,"fxstate",{fxstate:a});this.Lc=!1}async wf(a){const b=a.saveLoadMode;if(3!==b)for(var c of this.C)c.pa()&&1===
b||(c.pa()||2!==b)&&c.ka();for(const g of this.ca.values())for(const p of g)p.c();this.ca.clear();this.Ub=a.timeScale;this.Hc=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.la=a.isSilent;this.A.tb(this.la);this.Oc=a.masterVolume;c=[];for(const g of Object.values(a.effects))c.push(Promise.all(g.map(p=>this.od(p))));await Promise.all(c);await Promise.all(a.playing.map(g=>this.hf(g,b)));this.yb()}async hf(a,b){if(3!==b){var c=a.bufferOriginalUrl,g=a.bufferUrl,p=a.bufferType,
t=a.isMusic,d=a.tag,h=a.isLooping,n=a.volume,l=a.playbackTime;if(!t||1!==b)if(t||2!==b){b=null;try{b=await this.oc(c,g,p,d,t)}catch(q){console.error("[Construct 3] Audio: error loading audio state: ",q);return}b.Fe(a.pan);b.Play(h,n,l,0);a.isPlaying||b.Qa();b.sc(a)}}}yf(a,b){this.ua&&this.ua.disconnect();this.Pc=b.toLowerCase();this.ua=this.f.createMediaStreamSource(a);this.ua.connect(this.ed(this.Pc))}tf(){this.Gb||(this.Gb=this.f.createMediaStreamDestination(),this.Hb.connect(this.Gb));return this.Gb.stream}static se(a,
b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Me(a){return a*e}static qe(a){return Math.pow(10,a/20)}static dd(a){return Math.max(Math.min(self.da.qe(a),1),0)}static Ee(a){return Math.log(a)/Math.log(10)*20}static De(a){return self.da.Ee(Math.max(Math.min(a,1),0))}static yg(a,b){return 1-Math.exp(-b*a)}};self.qa.wa(self.da)}"use strict";function W(e){e.Mb||(e.Mb=e.rc());return e.Mb}
self.$c=class{constructor(e,a,b,c,g){this.i=e;this.ug=a;this.va=b;this.P=c;this.rg=g;this.Dc="";this.Mb=null}c(){this.Mb=this.i=null}rc(){}V(){return this.i.V()}ac(){return this.ug}Pa(){return this.va}$b(){return this.P}pa(){return this.rg}ea(){}};"use strict";
self.ke=class extends self.$c{constructor(e,a,b,c,g){super(e,a,b,c,g);this.Dc="html5";this.H=new Audio;this.H.crossOrigin="anonymous";this.H.autoplay=!1;this.H.preload="auto";this.ab=this.bb=null;this.H.addEventListener("canplaythrough",()=>!0);this.gb=this.V().createGain();this.eb=null;this.H.addEventListener("canplay",()=>{this.bb&&(this.bb(),this.ab=this.bb=null);!this.eb&&this.H&&(this.eb=this.V().createMediaElementSource(this.H),this.eb.connect(this.gb))});this.onended=null;this.H.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.H.addEventListener("error",p=>{console.error(`[Construct 3] Audio '${this.va}' error: `,p);this.ab&&(this.ab(p),this.ab=this.bb=null)})}c(){this.i.kd(this);this.gb.disconnect();this.gb=null;this.eb.disconnect();this.eb=null;this.H&&!this.H.paused&&this.H.pause();this.H=this.onended=null;super.c()}rc(){return new Promise((e,a)=>{this.bb=e;this.ab=a;this.H.src=this.va})}N(){return this.H}ea(){return this.H.duration}};"use strict";
async function ca(e){if(e.sa)return e.sa;var a=e.i.A;if("cordova"===a.J&&a.Be(e.va)&&"file:"===location.protocol)e.sa=await a.Xb(e.va);else{a=await fetch(e.va);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);e.sa=await a.arrayBuffer()}}async function da(e){if(e.aa)return e.aa;e.aa=await e.i.re(e.sa,e.tg);e.sa=null}
self.me=class extends self.$c{constructor(e,a,b,c,g,p){super(e,a,b,c,g);this.Dc="webaudio";this.aa=this.sa=null;this.tg=!!p}c(){this.i.kd(this);this.aa=this.sa=null;super.c()}async rc(){try{await ca(this),await da(this)}catch(e){console.error(`[Construct 3] Failed to load audio '${this.va}': `,e)}}ea(){return this.aa?this.aa.duration:0}};"use strict";
{let e=0;self.ad=class{constructor(a,b,c){this.i=a;this.K=b;this.$=c;this.Eb=e++;this.L=this.V().createGain();this.L.connect(this.oa());this.v=null;this.Za=!1;this.F=!0;this.U=this.ia=this.D=!1;this.kb=1;this.Da=!1;this.Z=1;a=this.i.Vc;this.Mc=1===a&&!this.pa()||2===a;this.Wa=this.fa=-1;this.Ud=!1}c(){this.K=this.i=null;this.v&&(this.v.disconnect(),this.v=null);this.L.disconnect();this.L=null}V(){return this.i.V()}oa(){return this.i.ed(this.$)}ob(){return this.i.ob()}nb(){return this.Mc?this.i.Hc:
performance.now()/1E3}ac(){return this.K.ac()}Pa(){return this.K.Pa()}$b(){return this.K.$b()}pa(){return this.K.pa()}Ke(a){this.$=a}S(){}Wb(){}IsPlaying(){return!this.F&&!this.D&&!this.S()}fd(){return!this.F&&!this.S()}ya(){}ea(){return this.K.ea()}Play(){}ka(){}Qa(){}rb(){}ub(a){this.kb=a;this.L.gain.cancelScheduledValues(0);this.Wa=-1;this.L.gain.value=this.bc()}te(a,b,c){if(!this.Da){a*=this.ob();var g=this.L.gain;g.cancelScheduledValues(0);var p=this.i.Zb();b=p+b;g.setValueAtTime(g.value,p);
g.linearRampToValueAtTime(a,b);this.kb=a;this.Wa=b;this.Ud=c}}Db(){this.ub(this.kb)}Aa(a){-1!==this.Wa&&a>=this.Wa&&(this.Wa=-1,this.Ud&&this.ka(),this.i.fc("fade-ended",this.$,this.Eb))}bc(){const a=this.kb*this.ob();return isFinite(a)?a:0}ld(a){a=!!a;this.Da!==a&&(this.Da=a,this.Cb())}pb(){return this.i.pb()}Cb(){}ic(){}nd(a){this.Z!==a&&(this.Z=a,this.Ba())}Ba(){}hc(){}jc(){}sb(a){a=!!a;this.Za!==a&&((this.Za=a)?(this.v||(this.v=this.V().createPanner(),this.v.panningModel=this.i.Pd,this.v.distanceModel=
this.i.Gd,this.v.refDistance=this.i.Qd,this.v.maxDistance=this.i.Od,this.v.rolloffFactor=this.i.Sd),this.L.disconnect(),this.L.connect(this.v),this.v.connect(this.oa())):(this.v.disconnect(),this.L.disconnect(),this.L.connect(this.oa())))}Je(a,b,c,g,p,t){this.Za&&(this.md(a,b,c),a=self.da.Me,this.v.coneInnerAngle=a(g),this.v.coneOuterAngle=a(p),this.v.coneOuterGain=t)}md(a,b,c){this.Za&&(this.v.setPosition(a,b,0),this.v.setOrientation(Math.cos(c),Math.sin(c),0))}Le(a){this.fa=a}cc(){}He(a){const b=
this.v||this.L;b.disconnect();b.connect(a)}Oa(){return{aiid:this.Eb,tag:this.$,duration:this.ea(),volume:this.kb,isPlaying:this.IsPlaying(),playbackTime:this.ya(),playbackRate:this.Z,uid:this.fa,bufferOriginalUrl:this.ac(),bufferUrl:"",bufferType:this.$b(),isMusic:this.pa(),isLooping:this.U,isMuted:this.Da,resumePosition:this.cc(),pan:this.ve()}}sc(a){this.nd(a.playbackRate);this.ld(a.isMuted)}ve(){if(!this.v)return null;const a=this.v;return{pos:[a.positionX.value,a.positionY.value,a.positionZ.value],
orient:[a.orientationX.value,a.orientationY.value,a.orientationZ.value],cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}Fe(a){a?(this.sb(!0),a=this.v,a.setPosition(...a.pos),a.setOrientation(...a.orient),a.coneInnerAngle=a.cia,a.coneOuterAngle=a.coa,a.coneOuterGain=a.cog,this.fa=a.uid):this.sb(!1)}}}"use strict";
self.le=class extends self.ad{constructor(e,a,b){super(e,a,b);this.K.gb.connect(this.L);this.K.onended=()=>this.uc()}c(){this.ka();this.K.gb.disconnect();super.c()}N(){return this.K.N()}uc(){this.F=!0;this.fa=-1;this.i.fc("ended",this.$,this.Eb)}S(){return this.N().ended}Wb(){return this.F?!0:this.S()}ya(e){let a=this.N().currentTime;e&&(a*=this.Z);this.U||(a=Math.min(a,this.ea()));return a}Play(e,a,b){const c=this.N();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==e&&(c.loop=e);this.ub(a);c.muted&&
(c.muted=!1);if(c.currentTime!==b)try{c.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.K.Pa()}' to position '${b}': `,g)}this.i.ra(c);this.D=this.F=!1;this.U=e;this.Z=1}ka(){const e=this.N();e.paused||e.pause();this.i.za(e);this.F=!0;this.D=!1;this.fa=-1}Qa(){if(!(this.D||this.F||this.S())){var e=this.N();e.paused||e.pause();this.i.za(e);this.D=!0}}rb(){!this.D||this.F||this.S()||(this.i.ra(this.N()),this.D=!1)}Cb(){this.N().muted=this.Da||this.pb()}ic(e){e=!!e;
this.U!==e&&(this.U=e,this.N().loop=e)}Ba(){let e=this.Z;this.Mc&&(e*=this.i.Ub);try{this.N().playbackRate=e}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${e}':`,a)}}hc(e){if(!this.F&&!this.S())try{this.N().currentTime=e}catch(a){console.warn(`[Construct 3] Error seeking audio to '${e}': `,a)}}cc(){return this.ya()}jc(e){e?this.IsPlaying()?(this.N().pause(),this.ia=!0):this.ia=!1:this.ia&&(this.i.ra(this.N()),this.ia=!1)}};"use strict";
function X(e){e.j&&e.j.disconnect();e.j=null;e.Sa=null}
self.ne=class extends self.ad{constructor(e,a,b){super(e,a,b);this.j=null;this.Pb=c=>this.uc(c);this.Ic=!0;this.Sa=null;this.M=this.Tb=0;this.Qc=1}c(){this.ka();X(this);this.Pb=null;super.c()}uc(e){this.D||this.ia||e.target!==this.Sa||(this.F=this.Ic=!0,this.fa=-1,X(this),this.i.fc("ended",this.$,this.Eb))}S(){return!this.F&&this.j&&this.j.loop||this.D?!1:this.Ic}Wb(){return!this.j||this.F?!0:this.S()}ya(e){let a;a=this.D?this.M:this.nb()-this.Tb;e&&(a*=this.Z);this.U||(a=Math.min(a,this.ea()));return a}Play(e,
a,b,c){this.Qc=1;this.ub(a);X(this);this.j=this.V().createBufferSource();this.j.buffer=this.K.aa;this.j.connect(this.L);this.Sa=this.j;this.j.onended=this.Pb;this.j.loop=e;this.j.start(c,b);this.D=this.F=this.Ic=!1;this.U=e;this.Z=1;this.Tb=this.nb()-b}ka(){if(this.j)try{this.j.stop(0)}catch(e){}this.F=!0;this.D=!1;this.fa=-1}Qa(){this.D||this.F||this.S()||(this.M=this.ya(!0),this.U&&(this.M%=this.ea()),this.D=!0,this.j.stop(0))}rb(){!this.D||this.F||this.S()||(X(this),this.j=this.V().createBufferSource(),
this.j.buffer=this.K.aa,this.j.connect(this.L),this.Sa=this.j,this.j.onended=this.Pb,this.j.loop=this.U,this.Db(),this.Ba(),this.Tb=this.nb()-this.M/(this.Z||.001),this.j.start(0,this.M),this.D=!1)}bc(){return super.bc()*this.Qc}Cb(){this.Qc=this.Da||this.pb()?0:1;this.Db()}ic(e){e=!!e;this.U!==e&&(this.U=e,this.j&&(this.j.loop=e))}Ba(){let e=this.Z;this.Mc&&(e*=this.i.Ub);this.j&&(this.j.playbackRate.value=e)}hc(e){this.F||this.S()||(this.D?this.M=e:(this.Qa(),this.M=e,this.rb()))}cc(){return this.M}jc(e){e?
this.IsPlaying()?(this.ia=!0,this.M=this.ya(!0),this.U&&(this.M%=this.ea()),this.j.stop(0)):this.ia=!1:this.ia&&(X(this),this.j=this.V().createBufferSource(),this.j.buffer=this.K.aa,this.j.connect(this.L),this.Sa=this.j,this.j.onended=this.Pb,this.j.loop=this.U,this.Db(),this.Ba(),this.Tb=this.nb()-this.M/(this.Z||.001),this.j.start(0,this.M),this.ia=!1)}sc(e){super.sc(e);this.M=e.resumePosition}};"use strict";
{class e{constructor(a){this.i=a;this.f=a.V();this.Jd=-1;this.P=this.$="";this.g=null}c(){this.f=null}Xf(a){this.Jd=a}eg(a){this.$=a}o(){return this.f.createGain()}O(){}R(){}m(a,b,c,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var p=this.f.currentTime;g+=p;switch(c){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,p);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,p),a.exponentialRampToValueAtTime(b,g)}}}Oa(){return{type:this.P,tag:this.$,params:this.g}}}
self.ee=class extends e{constructor(a,b,c,g,p,t,d){super(a);this.P="filter";this.g=[b,c,g,p,t,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=c;this.u.detune.value=g;this.u.Q.value=p;this.u.gain.vlaue=t;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}R(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[2]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[3]=b;this.m(this.u.Q,b,c,g);break;case 4:this.g[4]=b,this.m(this.u.gain,b,c,g)}}};self.ce=class extends e{constructor(a,b,c,g){super(a);this.P="delay";this.g=[b,c,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.cb=this.o();this.T=this.f.createDelay(b);this.T.delayTime.value=b;this.Va=this.o();this.Va.gain.value=c;this.l.connect(this.cb);this.l.connect(this.a);this.cb.connect(this.b);this.cb.connect(this.T);this.T.connect(this.Va);this.Va.connect(this.cb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.cb.disconnect();this.T.disconnect();this.Va.disconnect();super.c()}R(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,c,g){const p=self.da.dd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 4:this.g[1]=p(b);this.m(this.Va.gain,p(b),c,g);break;case 5:this.g[0]=b,this.m(this.T.delayTime,b,c,g)}}};self.be=class extends e{constructor(a,b,c,g){super(a);this.P="convolution";this.g=[c,g];this.Ed=this.Dd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.Ua=this.f.createConvolver();this.Ua.normalize=c;this.Ua.buffer=b;this.l.connect(this.Ua);this.l.connect(this.a);this.Ua.connect(this.b)}c(){this.l.disconnect();this.Ua.disconnect();this.b.disconnect();this.a.disconnect();super.c()}R(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}Tf(a,b){this.Dd=a;this.Ed=b}Oa(){const a=
super.Oa();a.bufferOriginalUrl=this.Dd;a.bufferUrl="";a.bufferType=this.Ed;return a}};self.fe=class extends e{constructor(a,b,c,g,p,t){super(a);this.P="flanger";this.g=[b,c,g,p,t];this.l=this.o();this.a=this.o();this.a.gain.value=1-t/2;this.b=this.o();this.b.gain.value=t/2;this.Xa=this.o();this.Xa.gain.value=p;this.T=this.f.createDelay(b+c);this.T.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.G=this.o();this.G.gain.value=c;this.l.connect(this.T);this.l.connect(this.a);
this.T.connect(this.b);this.T.connect(this.Xa);this.Xa.connect(this.T);this.s.connect(this.G);this.G.connect(this.T.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.T.disconnect();this.s.disconnect();this.G.disconnect();this.a.disconnect();this.b.disconnect();this.Xa.disconnect();super.c()}R(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 6:this.g[1]=b/1E3;this.m(this.G.gain,b/1E3,c,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,c,g);break;case 8:this.g[3]=b/100,this.m(this.Xa.gain,b/100,c,g)}}};self.he=class extends e{constructor(a,b,c,g,p,t,d){super(a);this.P="phaser";this.g=[b,c,g,p,t,d];this.l=this.o();this.a=this.o();this.a.gain.value=1-d/2;this.b=this.o();this.b.gain.value=d/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
c;this.u.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=t;this.G=this.o();this.G.gain.value=p;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.G);this.G.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.G.disconnect();this.a.disconnect();this.b.disconnect();super.c()}R(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,
b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[1]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[2]=b;this.m(this.u.Q,b,c,g);break;case 6:this.g[3]=b;this.m(this.G.gain,b,c,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,c,g)}}};self.ge=class extends e{constructor(a,b){super(a);this.P="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(a,b,c,g){const p=self.da.dd;switch(a){case 4:this.g[0]=p(b),this.m(this.h.gain,p(b),c,g)}}};self.je=class extends e{constructor(a,b,c){super(a);this.P="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.G=this.o();this.G.gain.value=c/2;this.s.connect(this.G);this.G.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.G.disconnect();this.h.disconnect();super.c()}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain.value,1-b/2,c,g);this.m(this.G.gain.value,b/2,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.ie=class extends e{constructor(a,b,c){super(a);this.P="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.jb=this.o();
this.jb.gain.value=0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.jb.gain);this.s.start(0);this.l.connect(this.jb);this.l.connect(this.a);this.jb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.jb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}R(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,
b,c,g);this.m(this.a.gain,1-b,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.de=class extends e{constructor(a,b,c,g,p,t){super(a);this.P="distortion";this.g=[b,c,g,p,t];this.l=this.o();this.Rb=this.o();this.Qb=this.o();this.Uf(g,p);this.b=this.o();this.b.gain.value=t;this.a=this.o();this.a.gain.value=1-t;this.Vb=this.f.createWaveShaper();this.Fc=new Float32Array(65536);this.cf(b,c);this.Vb.curve=this.Fc;this.l.connect(this.Rb);this.l.connect(this.a);this.Rb.connect(this.Vb);
this.Vb.connect(this.Qb);this.Qb.connect(this.b)}c(){this.l.disconnect();this.Rb.disconnect();this.Vb.disconnect();this.Qb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}Uf(a,b){.01>a&&(a=.01);this.Rb.gain.value=a;this.Qb.gain.value=Math.pow(1/a,.6)*b}cf(a,b){for(let c=0;32768>c;++c){let g=c/32768;g=this.gg(g,a,b);this.Fc[32768+c]=g;this.Fc[32768-c-1]=-g}}gg(a,b,c){c=1.05*c*b-b;const g=0>a?-a:a;return(g<b?g:b+c*self.da.yg(g-b,1/c))*(0>a?-1:1)}R(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}};self.ae=class extends e{constructor(a,b,c,g,p,t){super(a);this.P="compressor";this.g=[b,c,g,p,t];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=g;this.h.attack.value=p;this.h.release.value=t}c(){this.h.disconnect();super.c()}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(){}};
self.$d=class extends e{constructor(a,b,c){super(a);this.P="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Hd=new Float32Array(this.h.frequencyBinCount);this.Td=new Uint8Array(b);this.Rd=this.Ga=0;this.i.Ne(this)}c(){this.i.Nf(this);this.h.disconnect();super.c()}Aa(){this.h.getFloatFrequencyData(this.Hd);this.h.getByteTimeDomainData(this.Td);const a=this.h.fftSize;let b=this.Ga=0;for(var c=0;c<a;++c){let g=(this.Td[c]-128)/128;0>g&&(g=-g);
this.Ga<g&&(this.Ga=g);b+=g*g}c=self.da.De;this.Ga=c(this.Ga);this.Rd=c(Math.sqrt(b/a))}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(){}ue(){return{tag:this.$,index:this.Jd,peak:this.Ga,rms:this.Rd,binCount:this.h.frequencyBinCount,freqBins:this.Hd}}}}"use strict";function ea(e){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>v(e,"sw-message",a.data))}
function fa(e){e=e.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(e):screen.webkitLockOrientation?a=screen.webkitLockOrientation(e):screen.mozLockOrientation?a=screen.mozLockOrientation(e):screen.msLockOrientation&&(a=screen.msLockOrientation(e));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.qa.wa(class extends self.xa{constructor(e){super(e,"browser");this.J="";B(this,[["get-initial-state",a=>{this.J=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>ea(this)],
["alert",a=>this.tc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.zc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>fa(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===b)window.forward();else if("home"===b)window.home();else if("reload"===b)location.reload();else if("url"===b){b=a.url;var c=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a?window.open(b,"_blank"):this.Kg||(2===c?window.top.location=b:1===c?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,c=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,c))}],["request-fullscreen",
a=>{{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?document.exitFullscreen():
document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{v(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{v(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{v(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",
()=>{v(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",a=>{a.handled=!0;v(this,"backbutton")})}tc(e){alert(e.message)}zc(e){e=e.isFocus;if("nwjs"===this.J){const a="nwjs"===this.J?nw.Window.get():null;e?a.focus():a.blur()}else e?window.focus():window.blur()}});"use strict";function Y(e){13!==e.which&&27!==e.which&&e.stopPropagation()}function Z(e){e.stopPropagation()}
self.qa.wa(class extends self.pe{constructor(e){super(e,"text-input");G(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}cd(e,a){let b;const c=a.type;"textarea"===c?(b=document.createElement("textarea"),b.style.resize="none"):(b=document.createElement("input"),b.type=c);b.style.position="absolute";b.autocomplete="off";b.addEventListener("touchstart",Z);b.addEventListener("touchmove",Z);b.addEventListener("touchend",Z);b.addEventListener("mousedown",Z);b.addEventListener("mouseup",Z);b.addEventListener("keydown",
Y);b.addEventListener("keyup",Y);b.addEventListener("click",g=>{g.stopPropagation();H(this,"click",e)});b.addEventListener("dblclick",g=>{g.stopPropagation();H(this,"dblclick",e)});b.addEventListener("input",()=>F(this,"change",e,{text:b.value}));a.id&&(b.id=a.id);this.lc(b,a);return b}lc(e,a){e.value=a.text;e.placeholder=a.placeholder;e.title=a.title;e.disabled=!a.isEnabled;e.readOnly=a.isReadOnly;e.spellcheck=a.spellCheck;a=a.maxLength;0>a?e.removeAttribute("maxlength"):e.setAttribute("maxlength",
a)}});"use strict";self.qa.wa(class extends self.xa{constructor(e){super(e,"mouse");A(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";async function ha(e,a){a=a.type;let b=!0;0===a?b=await ia():1===a&&(b=await ja());v(e,"permission-result",{type:a,result:b})}
async function ia(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request orientation permission: ",e),!1}}
async function ja(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request motion permission: ",e),!1}}self.qa.wa(class extends self.xa{constructor(e){super(e,"touch");A(this,"request-permission",a=>ha(this,a))}});